// <auto-generated />
using ColorsApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ColorsApi.Migrations
{
    [DbContext(typeof(ColorDbContext))]
    [Migration("20250403122134_RemoveFK")]
    partial class RemoveFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ColorsApi.Entities.ColorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Blue")
                        .HasColumnType("integer");

                    b.Property<int>("ColorPaletteEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("Green")
                        .HasColumnType("integer");

                    b.Property<int>("Red")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColorPaletteEntityId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("ColorsApi.Entities.ColorPaletteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Palettes");
                });

            modelBuilder.Entity("ColorsApi.Entities.ColorEntity", b =>
                {
                    b.HasOne("ColorsApi.Entities.ColorPaletteEntity", null)
                        .WithMany("Colors")
                        .HasForeignKey("ColorPaletteEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColorsApi.Entities.ColorPaletteEntity", b =>
                {
                    b.Navigation("Colors");
                });
#pragma warning restore 612, 618
        }
    }
}
